version: '3.7'

services:

  showcases:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      REACT_APP_REACT_ENV: PROD

  anomalies:
    container_name: anomalies
    build:
      context: ./anomalies
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    environment:
      JULIA_ENV: PROD
