version: '3'

networks:
  reddit-stream_middleware-network:
    external: true


services:

  temperature_middleware:
    container_name: temperature_middleware
    build:
      context: ./middleware
      dockerfile: Dockerfile
    networks:
      - reddit-stream_middleware-network
    env_file: ./middleware/.env
    restart: on-failure
    ports:
      - "8764:8764"
